name: Build and Upload Artifact

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
#        os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify the desired Node.js version

      - name: Install dependencies
        run: npm install
        
      - name: Install archiver package
        run: npm install archiver
        
      - name: Run build script
        run: node build.js

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin-active-win-${{ matrix.os }}
          path: plugin-active-win.zip
