name: Build and Upload Artifact

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify the desired Node.js version

      - name: Install dependencies
        run: npm install
        
      - name: Remove unused dependencies
        run: |
          echo "Removing unused dependencies..."
          node -e " \
            const fs = require('fs'); \
            const lockfile = require('./package-lock-grid.json'); \
            const modules = fs.readdirSync('node_modules'); \
            for (const module of modules) { \
              if (lockfile.dependencies[module]) { \
                fs.rmSync('node_modules/' + module, { recursive: true, force: true }); \
              } \
            } \
            console.log('Unused dependencies removed.'); \
          "

      - name: Zip files
        run: zip -r my-project-${{ matrix.os }}.zip .  # Adjust the ZIP file name as needed

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: plugin-result
          path: |
            my-project-ubuntu-latest.zip
            my-project-windows-latest.zip
            my-project-macos-latest.zip
