name: Build and Upload Artifact

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
#        os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify the desired Node.js version

      - name: Install dependencies
        run: npm install
        
      - name: Run build script
        run: node build.js
        
      - name: Zip files (Linux and macOS)
        if: matrix.os != 'windows-latest'
        run: zip -r my-project.zip .

      - name: Zip files (Windows)
        if: matrix.os == 'windows-latest'
        run: powershell -Command "Compress-Archive -Path '.' -DestinationPath 'my-project.zip'"


      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-project-${{ matrix.os }}
          path: my-project.zip
