name: Build and Upload Artifact

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify the desired Node.js version

      - name: Install dependencies
        run: npm install
        
      - name: Remove dependencies
        run: |
          echo "Removing dependencies..."
          node -e "const fs = require('fs')"
          node -e "const lockfile = require('./package-lock.json')"
          node -e "const modules = fs.readdirSync('node_modules')"
          node -e "for (const dependency in lockfile.dependencies) {"
          node -e "  if (modules.includes(dependency)) {"
          node -e "    fs.rmSync('node_modules/' + dependency, { recursive: true, force: true })"
          node -e "  }"
          node -e "}"
          node -e "console.log('Dependencies removed.');"

      - name: Zip files
        run: zip -r my-project-${{ matrix.os }}.zip .  # Adjust the ZIP file name as needed

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: plugin-result
          path: |
            my-project-ubuntu-latest.zip
            my-project-windows-latest.zip
            my-project-macos-latest.zip
