name: Build and Upload Artifact

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
#        os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify the desired Node.js version

      - name: Install dependencies
        run: npm install
        
      - name: Install archiver package
        run: npm install archiver
        
      - name: Run build script
        run: node build.js
        
#      - name: Zip files (Linux and macOS)
#        if: matrix.os != 'windows-latest'
#        run: zip -r plugin-active-win.zip . -x 'archive.js' 'build.js' 'package-lock-grid.json' '.github/*'
#
#      - name: Remove files (Windows)
#        if: matrix.os == 'windows-latest'
#        run: robocopy . temp /e /xf archive.js build.js package-lock-grid.json /xd .github
#
#      - name: Zip files (Windows)
#        if: matrix.os == 'windows-latest'
#        run: powershell -Command "Compress-Archive -Path 'temp' -DestinationPath 'plugin-active-win.zip'"


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin-active-win-${{ matrix.os }}
          path: plugin-active-win.zip
