name: Build and Upload Artifact

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.save_output.outputs.upload_url  }}
      release_id: ${{ steps.save_output.outputs.release_id  }}
    steps:
      - name: Delete all releases
        # You may pin to the exact commit or the version.
        # uses: amol234545/auto-bulid-exe@fa51f02942d8ff9626aadf83dd2621a4e2193391
        uses: larryjoelane/delete-release-action@v1.0.24
        with:
          release-name: v0.0.1
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.1
          release_name: Release 0.0.1
          body: |
            Test release.
          draft: false
          prerelease: false
      - name: Save release output
        id: save_output
        run: |
          echo "upload_url=${{ steps.create_release.outputs.upload_url  }}" >> "$GITHUB_OUTPUT"
          echo "release_id=${{ steps.create_release.outputs.id  }}" >> "$GITHUB_OUTPUT"
  
  build:
    runs-on: ${{ matrix.os }}
    needs: create-github-release 
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
#        os: [macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify the desired Node.js version

      - name: Install dependencies
        run: npm install
        
      - name: Install archiver package
        run: npm install archiver
        
      - name: Run build script
        run: node build.js
                
      - name: Upload Artifact
        uses: tanyagray/action-upload-release-asset@v1.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-github-release.outputs.upload_url }}
          asset_path: plugin-active-win.zip
          asset_name: plugin-active-win-${{ matrix.os }}.zip
          asset_content_type: application/zip
  publish-release:
    needs: [build, create-github-release]
    runs-on: ubuntu-latest
    steps:
    - name: Publish Release
      uses: eregon/publish-release@v1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ needs.create-github-release.outputs.release_id}}
